import { MapPin } from "./types";

export const mockMapPins: MapPin[] = [
  {
    id: "mp1",
    title: "ETH Main Library",
    category: "suggestion",
    description: "Great silent study floors, solid wifi, open late on weekdays.",
    city: "Zurich",
    area: "Zentrum",
    address: "Rämistrasse 101, 8092 Zürich",
    lat: 47.3763,
    lng: 8.5480,
  },
  {
    id: "mp2",
    title: "Volkshaus Zürich",
    category: "suggestion",
    description: "Relaxed café + bar with good lunch options. Popular after-class spot.",
    city: "Zurich",
    area: "Langstrasse",
    address: "Stauffacherstrasse 60, 8004 Zürich",
    lat: 47.3762,
    lng: 8.5288,
  },
  {
    id: "mp3",
    title: "Lindenhügel",
    category: "meetup",
    description: "Classic Zurich meetup hill. Easy for everyone to find, great views.",
    city: "Zurich",
    area: "Altstadt",
    address: "Lindenhügel, 8001 Zürich",
    lat: 47.3728,
    lng: 8.5411,
  },
  {
    id: "mp4",
    title: "Bürkliplatz",
    category: "meetup",
    description: "Central lakeside square. Good start point for walks or market days.",
    city: "Zurich",
    area: "City Center",
    address: "Bürkliplatz, 8001 Zürich",
    lat: 47.3659,
    lng: 8.5432,
  },
  {
    id: "mp5",
    title: "Café Sprüngli",
    category: "suggestion",
    description: "Iconic Zurich café. Good for a coffee catch-up, busy on weekends.",
    city: "Zurich",
    area: "Paradeplatz",
    address: "Bahnhofstrasse 21, 8001 Zürich",
    lat: 47.3693,
    lng: 8.5387,
  },
  {
    id: "mp6",
    title: "Zürichsee Promenade",
    category: "suggestion",
    description: "Flat lakeside walk, great any time of day. Easy for any group size.",
    city: "Zurich",
    area: "Seefeld",
    address: "Utoquai, 8008 Zürich",
    lat: 47.3579,
    lng: 8.5490,
  },
  {
    id: "mp7",
    title: "Longstreet Bar",
    category: "suggestion",
    description: "Casual bar in Langstrasse. Good for weeknight drinks, no dress code.",
    city: "Zurich",
    area: "Langstrasse",
    address: "Langstrasse 92, 8004 Zürich",
    lat: 47.3781,
    lng: 8.5271,
  },
  {
    id: "mp8",
    title: "Alpenquai",
    category: "meetup",
    description: "Quiet lake spot away from crowds. Good for a casual hangout or swim in summer.",
    city: "Zurich",
    area: "Enge",
    address: "Alpenquai, 8038 Zürich",
    lat: 47.3520,
    lng: 8.5370,
  },
];